export const REQ = 'REQ'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'


export const SUCCESSMONTH = 'SUCCESSMONTH'

export const SUCCESSWEEK = 'SUCCESSWEEK'

export const SUCCESSEQUIMENT = 'SUCCESSEQUIMENT'


export const SUCCESSSERVICE = 'SUCCESSSERVICE'

export const SUCCESSSERVICEDETAIL = 'SUCCESSSERVICEDETAIL'


export const SUCCESSNUMBERLEVEL = 'SUCCESSNUMBERLEVEL'

export const SUCCESSREPORT = 'SUCCESSREPORT'

export const SUCCESSROLE = 'SUCCESSREROLE'

export const SUCCESSUSERLIST = 'SUCCESSUSERLIST'

export const SUCCESSUSERDIARY = 'SUCCESSUSERDIARY'

export const SENDDATADETIAL = 'SENDDATADETIAL'



export const SENDDATAROLE= 'SENDDATAROLE'


